version = 0.1

[default]
[default.global.parameters]
stack_name = "sam-app"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
resolve_image_repos = true

[default.package.parameters]
resolve_s3 = true
